# Generated by Django 4.2.1 on 2023-06-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de producto')),
                ('Categoria', models.CharField(max_length=10, verbose_name='Categoría')),
                ('Precio', models.IntegerField(max_length=9, verbose_name='Precio')),
                ('DescuentoSubscriptor', models.IntegerField(max_length=2, verbose_name='Descuento Subscriptor %')),
                ('DescuentoOferta', models.IntegerField(max_length=2, verbose_name='Descuento por Oferta')),
            ],
        ),
    ]
