# Generated by Django 4.2.1 on 2023-06-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='DescuentoOferta',
            field=models.IntegerField(verbose_name='Descuento por Oferta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='DescuentoSubscriptor',
            field=models.IntegerField(verbose_name='Descuento Subscriptor %'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='Precio',
            field=models.IntegerField(verbose_name='Precio'),
        ),
    ]
