# Generated by Django 4.2.1 on 2023-06-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_descuentooferta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Descripcion',
            field=models.CharField(default='Lol', max_length=300, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='Nombre',
            field=models.CharField(default='lol', max_length=50, verbose_name='Nombre Producto'),
            preserve_default=False,
        ),
    ]
