# Generated by Django 4.2.1 on 2023-06-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_producto_descripcion_producto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de producto')),
                ('TipoUsuario', models.CharField(max_length=20)),
                ('Rut', models.CharField(max_length=20)),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=500)),
                ('Suscripcion', models.BooleanField()),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
